interface CryptoData {
  id: string;
  name: string;
  symbol: string;
  network: string;
  icon: string;
  iconUrl?: string;
  networkIconUrl?: string;
  color: string;
}

export const cryptoDataList: CryptoData[] = [
  // Стейблкоины в разных сетях
  { id: '1', name: 'Tether (TRC20)', symbol: 'USDT', network: 'TRC20', icon: '₮', iconUrl: 'https://cdn.poehali.dev/files/64ba7feb-f8b0-4f82-8ed8-a8b33c26c00d.png', networkIconUrl: 'https://cryptologos.cc/logos/tron-trx-logo.png', color: 'text-green-600' },
  { id: '106', name: 'Tether (ERC20)', symbol: 'USDT', network: 'ERC20', icon: '₮', iconUrl: 'https://cdn.poehali.dev/files/64ba7feb-f8b0-4f82-8ed8-a8b33c26c00d.png', networkIconUrl: 'https://cryptologos.cc/logos/ethereum-eth-logo.png', color: 'text-green-600' },
  { id: '107', name: 'Tether (Solana)', symbol: 'USDT', network: 'Solana', icon: '₮', iconUrl: 'https://cdn.poehali.dev/files/64ba7feb-f8b0-4f82-8ed8-a8b33c26c00d.png', networkIconUrl: 'https://cryptologos.cc/logos/solana-sol-logo.png', color: 'text-green-600' },
  { id: '108', name: 'Tether (BEP20)', symbol: 'USDT', network: 'BEP20', icon: '₮', iconUrl: 'https://cdn.poehali.dev/files/64ba7feb-f8b0-4f82-8ed8-a8b33c26c00d.png', networkIconUrl: 'https://cryptologos.cc/logos/bnb-bnb-logo.png', color: 'text-green-600' },
  { id: '109', name: 'Tether (Polygon)', symbol: 'USDT', network: 'Polygon', icon: '₮', iconUrl: 'https://cdn.poehali.dev/files/64ba7feb-f8b0-4f82-8ed8-a8b33c26c00d.png', networkIconUrl: 'https://cryptologos.cc/logos/polygon-matic-logo.png', color: 'text-green-600' },
  { id: '110', name: 'Tether (Avalanche)', symbol: 'USDT', network: 'Avalanche', icon: '₮', iconUrl: 'https://cdn.poehali.dev/files/64ba7feb-f8b0-4f82-8ed8-a8b33c26c00d.png', networkIconUrl: 'https://cryptologos.cc/logos/avalanche-avax-logo.png', color: 'text-green-600' },
  { id: '111', name: 'USD Coin (ERC20)', symbol: 'USDC', network: 'ERC20', icon: 'C', iconUrl: 'https://cryptologos.cc/logos/usd-coin-usdc-logo.png', networkIconUrl: 'https://cryptologos.cc/logos/ethereum-eth-logo.png', color: 'text-blue-600' },
  { id: '112', name: 'USD Coin (Solana)', symbol: 'USDC', network: 'Solana', icon: 'C', iconUrl: 'https://cryptologos.cc/logos/usd-coin-usdc-logo.png', networkIconUrl: 'https://cryptologos.cc/logos/solana-sol-logo.png', color: 'text-blue-600' },
  { id: '113', name: 'USD Coin (BEP20)', symbol: 'USDC', network: 'BEP20', icon: 'C', iconUrl: 'https://cryptologos.cc/logos/usd-coin-usdc-logo.png', networkIconUrl: 'https://cryptologos.cc/logos/bnb-bnb-logo.png', color: 'text-blue-600' },
  { id: '114', name: 'USD Coin (Polygon)', symbol: 'USDC', network: 'Polygon', icon: 'C', iconUrl: 'https://cryptologos.cc/logos/usd-coin-usdc-logo.png', networkIconUrl: 'https://cryptologos.cc/logos/polygon-matic-logo.png', color: 'text-blue-600' },
  { id: '115', name: 'Dai (ERC20)', symbol: 'DAI', network: 'ERC20', icon: 'D', iconUrl: 'https://cryptologos.cc/logos/multi-collateral-dai-dai-logo.png', networkIconUrl: 'https://cryptologos.cc/logos/ethereum-eth-logo.png', color: 'text-yellow-600' },
  { id: '116', name: 'Dai (BEP20)', symbol: 'DAI', network: 'BEP20', icon: 'D', iconUrl: 'https://cryptologos.cc/logos/multi-collateral-dai-dai-logo.png', networkIconUrl: 'https://cryptologos.cc/logos/bnb-bnb-logo.png', color: 'text-yellow-600' },
  { id: '117', name: 'Binance USD (BEP20)', symbol: 'BUSD', network: 'BEP20', icon: 'B', iconUrl: 'https://cryptologos.cc/logos/binance-usd-busd-logo.png', networkIconUrl: 'https://cryptologos.cc/logos/bnb-bnb-logo.png', color: 'text-yellow-600' },
  { id: '118', name: 'TrueUSD (ERC20)', symbol: 'TUSD', network: 'ERC20', icon: 'T', iconUrl: 'https://cryptologos.cc/logos/trueusd-tusd-logo.png', networkIconUrl: 'https://cryptologos.cc/logos/ethereum-eth-logo.png', color: 'text-blue-600' },
  { id: '119', name: 'TrueUSD (TRC20)', symbol: 'TUSD', network: 'TRC20', icon: 'T', iconUrl: 'https://cryptologos.cc/logos/trueusd-tusd-logo.png', networkIconUrl: 'https://cryptologos.cc/logos/tron-trx-logo.png', color: 'text-blue-600' },
  { id: '120', name: 'Pax Dollar (ERC20)', symbol: 'USDP', network: 'ERC20', icon: 'P', iconUrl: 'https://cryptologos.cc/logos/paxos-standard-pax-logo.png', networkIconUrl: 'https://cryptologos.cc/logos/ethereum-eth-logo.png', color: 'text-green-600' },
  { id: '121', name: 'Gemini Dollar (ERC20)', symbol: 'GUSD', network: 'ERC20', icon: 'G', iconUrl: 'https://cryptologos.cc/logos/gemini-dollar-gusd-logo.png', networkIconUrl: 'https://cryptologos.cc/logos/ethereum-eth-logo.png', color: 'text-blue-600' },
  { id: '122', name: 'Frax (ERC20)', symbol: 'FRAX', network: 'ERC20', icon: 'F', iconUrl: 'https://cryptologos.cc/logos/frax-frax-logo.png', networkIconUrl: 'https://cryptologos.cc/logos/ethereum-eth-logo.png', color: 'text-gray-700' },
  { id: '123', name: 'Frax (BEP20)', symbol: 'FRAX', network: 'BEP20', icon: 'F', iconUrl: 'https://cryptologos.cc/logos/frax-frax-logo.png', networkIconUrl: 'https://cryptologos.cc/logos/bnb-bnb-logo.png', color: 'text-gray-700' },
  { id: '124', name: 'USDD (TRC20)', symbol: 'USDD', network: 'TRC20', icon: 'U', iconUrl: 'https://cryptologos.cc/logos/usdd-usdd-logo.png', networkIconUrl: 'https://cryptologos.cc/logos/tron-trx-logo.png', color: 'text-gray-700' },
  
  // Основные криптовалюты
  { id: '2', name: 'Bitcoin', symbol: 'BTC', network: 'Bitcoin', icon: '₿', iconUrl: 'https://cryptologos.cc/logos/bitcoin-btc-logo.png', color: 'text-orange-500' },
  { id: '3', name: 'Ethereum', symbol: 'ETH', network: 'Ethereum', icon: 'Ξ', iconUrl: 'https://cryptologos.cc/logos/ethereum-eth-logo.png', color: 'text-blue-600' },
  { id: '4', name: 'BNB', symbol: 'BNB', network: 'BSC', icon: '🔶', iconUrl: 'https://cryptologos.cc/logos/bnb-bnb-logo.png', color: 'text-yellow-600' },
  { id: '5', name: 'Cardano', symbol: 'ADA', network: 'Cardano', icon: '₳', iconUrl: 'https://cryptologos.cc/logos/cardano-ada-logo.png', color: 'text-blue-500' },
  { id: '6', name: 'Solana', symbol: 'SOL', network: 'Solana', icon: '◎', iconUrl: 'https://cryptologos.cc/logos/solana-sol-logo.png', color: 'text-purple-600' },
  { id: '7', name: 'Ripple', symbol: 'XRP', network: 'XRP Ledger', icon: '✕', iconUrl: 'https://cryptologos.cc/logos/xrp-xrp-logo.png', color: 'text-gray-600' },
  { id: '8', name: 'Polkadot', symbol: 'DOT', network: 'Polkadot', icon: '●', iconUrl: 'https://cryptologos.cc/logos/polkadot-new-dot-logo.png', color: 'text-pink-600' },
  { id: '9', name: 'Dogecoin', symbol: 'DOGE', network: 'Dogecoin', icon: 'Ð', iconUrl: 'https://cryptologos.cc/logos/dogecoin-doge-logo.png', color: 'text-yellow-500' },
  { id: '10', name: 'Polygon', symbol: 'MATIC', network: 'Polygon', icon: '⬡', iconUrl: 'https://cryptologos.cc/logos/polygon-matic-logo.png', color: 'text-purple-500' },
  { id: '11', name: 'Litecoin', symbol: 'LTC', network: 'Litecoin', icon: 'Ł', iconUrl: 'https://cryptologos.cc/logos/litecoin-ltc-logo.png', color: 'text-gray-500' },
  { id: '12', name: 'Chainlink', symbol: 'LINK', network: 'Ethereum', icon: '⬢', iconUrl: 'https://cryptologos.cc/logos/chainlink-link-logo.png', color: 'text-blue-700' },
  { id: '13', name: 'Avalanche', symbol: 'AVAX', network: 'Avalanche', icon: '🔺', iconUrl: 'https://cryptologos.cc/logos/avalanche-avax-logo.png', color: 'text-red-600' },
  { id: '14', name: 'Cosmos', symbol: 'ATOM', network: 'Cosmos', icon: '⚛', iconUrl: 'https://cryptologos.cc/logos/cosmos-atom-logo.png', color: 'text-indigo-600' },
  { id: '15', name: 'Tron', symbol: 'TRX', network: 'Tron', icon: '◬', iconUrl: 'https://cryptologos.cc/logos/tron-trx-logo.png', color: 'text-red-700' },
  { id: '16', name: 'Monero', symbol: 'XMR', network: 'Monero', icon: 'ɱ', iconUrl: 'https://cryptologos.cc/logos/monero-xmr-logo.png', color: 'text-orange-700' },
  { id: '17', name: 'Stellar', symbol: 'XLM', network: 'Stellar', icon: '*', iconUrl: 'https://cryptologos.cc/logos/stellar-xlm-logo.png', color: 'text-cyan-600' },
  { id: '18', name: 'VeChain', symbol: 'VET', network: 'VeChain', icon: 'V', iconUrl: 'https://cryptologos.cc/logos/vechain-vet-logo.png', color: 'text-blue-800' },
  { id: '19', name: 'Algorand', symbol: 'ALGO', network: 'Algorand', icon: '▲', iconUrl: 'https://cryptologos.cc/logos/algorand-algo-logo.png', color: 'text-gray-700' },
  { id: '20', name: 'Filecoin', symbol: 'FIL', network: 'Filecoin', icon: '⨎', iconUrl: 'https://cryptologos.cc/logos/filecoin-fil-logo.png', color: 'text-cyan-700' },
  { id: '21', name: 'Hedera', symbol: 'HBAR', network: 'Hedera', icon: 'ℏ', iconUrl: 'https://cryptologos.cc/logos/hedera-hbar-logo.png', color: 'text-purple-700' },
  { id: '22', name: 'Near', symbol: 'NEAR', network: 'Near', icon: 'N', iconUrl: 'https://cryptologos.cc/logos/near-protocol-near-logo.png', color: 'text-green-700' },
  { id: '23', name: 'Fantom', symbol: 'FTM', network: 'Fantom', icon: '👻', iconUrl: 'https://cryptologos.cc/logos/fantom-ftm-logo.png', color: 'text-blue-900' },
  { id: '24', name: 'Aptos', symbol: 'APT', network: 'Aptos', icon: 'A', iconUrl: 'https://cryptologos.cc/logos/aptos-apt-logo.png', color: 'text-teal-600' },
  { id: '25', name: 'Optimism', symbol: 'OP', network: 'Optimism', icon: '🔴', iconUrl: 'https://cryptologos.cc/logos/optimism-ethereum-op-logo.png', color: 'text-red-500' },
  { id: '26', name: 'Arbitrum', symbol: 'ARB', network: 'Arbitrum', icon: '🔵', iconUrl: 'https://cryptologos.cc/logos/arbitrum-arb-logo.png', color: 'text-blue-600' },
  { id: '27', name: 'Sui', symbol: 'SUI', network: 'Sui', icon: '💧', iconUrl: 'https://cryptologos.cc/logos/sui-sui-logo.png', color: 'text-cyan-500' },
  { id: '28', name: 'Immutable', symbol: 'IMX', network: 'Ethereum', icon: '⬢', iconUrl: 'https://cryptologos.cc/logos/immutable-x-imx-logo.png', color: 'text-indigo-700' },
  { id: '29', name: 'Lido DAO', symbol: 'LDO', network: 'Ethereum', icon: '◉', iconUrl: 'https://cryptologos.cc/logos/lido-dao-ldo-logo.png', color: 'text-orange-500' },
  { id: '30', name: 'Toncoin', symbol: 'TON', network: 'TON', icon: '💎', iconUrl: 'https://cryptologos.cc/logos/toncoin-ton-logo.png', color: 'text-blue-400' },
  { id: '31', name: 'Uniswap', symbol: 'UNI', network: 'Ethereum', icon: '🦄', iconUrl: 'https://cryptologos.cc/logos/uniswap-uni-logo.png', color: 'text-pink-500' },
  { id: '32', name: 'Shiba Inu', symbol: 'SHIB', network: 'Ethereum', icon: '🐕', iconUrl: 'https://cryptologos.cc/logos/shiba-inu-shib-logo.png', color: 'text-orange-600' },
  { id: '33', name: 'Bitcoin Cash', symbol: 'BCH', network: 'Bitcoin Cash', icon: '₿', iconUrl: 'https://cryptologos.cc/logos/bitcoin-cash-bch-logo.png', color: 'text-green-500' },
  { id: '34', name: 'Ethereum Classic', symbol: 'ETC', network: 'Ethereum Classic', icon: 'Ξ', iconUrl: 'https://cryptologos.cc/logos/ethereum-classic-etc-logo.png', color: 'text-green-700' },
  { id: '35', name: 'Aave', symbol: 'AAVE', network: 'Ethereum', icon: 'A', iconUrl: 'https://cryptologos.cc/logos/aave-aave-logo.png', color: 'text-purple-600' },
  { id: '36', name: 'The Graph', symbol: 'GRT', network: 'Ethereum', icon: 'G', iconUrl: 'https://cryptologos.cc/logos/the-graph-grt-logo.png', color: 'text-blue-600' },
  { id: '37', name: 'Maker', symbol: 'MKR', network: 'Ethereum', icon: 'M', iconUrl: 'https://cryptologos.cc/logos/maker-mkr-logo.png', color: 'text-teal-600' },
  { id: '38', name: 'Curve', symbol: 'CRV', network: 'Ethereum', icon: 'C', iconUrl: 'https://cryptologos.cc/logos/curve-dao-token-crv-logo.png', color: 'text-blue-500' },
  { id: '39', name: 'PancakeSwap', symbol: 'CAKE', network: 'BSC', icon: '🥞', iconUrl: 'https://cryptologos.cc/logos/pancakeswap-cake-logo.png', color: 'text-yellow-700' },
  { id: '40', name: 'Synthetix', symbol: 'SNX', network: 'Ethereum', icon: 'S', iconUrl: 'https://cryptologos.cc/logos/synthetix-snx-logo.png', color: 'text-cyan-600' },
  { id: '41', name: 'Zcash', symbol: 'ZEC', network: 'Zcash', icon: 'Z', iconUrl: 'https://cryptologos.cc/logos/zcash-zec-logo.png', color: 'text-yellow-600' },
  { id: '42', name: 'Dash', symbol: 'DASH', network: 'Dash', icon: 'D', iconUrl: 'https://cryptologos.cc/logos/dash-dash-logo.png', color: 'text-blue-600' },
  { id: '43', name: 'Decentraland', symbol: 'MANA', network: 'Ethereum', icon: 'M', iconUrl: 'https://cryptologos.cc/logos/decentraland-mana-logo.png', color: 'text-red-500' },
  { id: '44', name: 'The Sandbox', symbol: 'SAND', network: 'Ethereum', icon: 'S', iconUrl: 'https://cryptologos.cc/logos/the-sandbox-sand-logo.png', color: 'text-cyan-500' },
  { id: '45', name: 'Axie Infinity', symbol: 'AXS', network: 'Ethereum', icon: 'A', iconUrl: 'https://cryptologos.cc/logos/axie-infinity-axs-logo.png', color: 'text-blue-600' },
  { id: '46', name: 'Theta', symbol: 'THETA', network: 'Theta', icon: 'Θ', iconUrl: 'https://cryptologos.cc/logos/theta-theta-logo.png', color: 'text-cyan-600' },
  { id: '47', name: 'EOS', symbol: 'EOS', network: 'EOS', icon: 'E', iconUrl: 'https://cryptologos.cc/logos/eos-eos-logo.png', color: 'text-gray-700' },
  { id: '48', name: 'Tezos', symbol: 'XTZ', network: 'Tezos', icon: 'T', iconUrl: 'https://cryptologos.cc/logos/tezos-xtz-logo.png', color: 'text-blue-600' },
  { id: '49', name: 'IOTA', symbol: 'MIOTA', network: 'IOTA', icon: 'I', iconUrl: 'https://cryptologos.cc/logos/iota-miota-logo.png', color: 'text-gray-600' },
  { id: '50', name: 'NEO', symbol: 'NEO', network: 'NEO', icon: 'N', iconUrl: 'https://cryptologos.cc/logos/neo-neo-logo.png', color: 'text-green-600' },
  { id: '51', name: 'Compound', symbol: 'COMP', network: 'Ethereum', icon: 'C', iconUrl: 'https://cryptologos.cc/logos/compound-comp-logo.png', color: 'text-green-500' },
  { id: '52', name: 'Quant', symbol: 'QNT', network: 'Ethereum', icon: 'Q', iconUrl: 'https://cryptologos.cc/logos/quant-qnt-logo.png', color: 'text-gray-700' },
  { id: '53', name: 'BitTorrent', symbol: 'BTT', network: 'Tron', icon: 'B', iconUrl: 'https://cryptologos.cc/logos/bittorrent-btt-logo.png', color: 'text-gray-600' },
  { id: '54', name: 'Flow', symbol: 'FLOW', network: 'Flow', icon: 'F', iconUrl: 'https://cryptologos.cc/logos/flow-flow-logo.png', color: 'text-green-500' },
  { id: '55', name: 'Elrond', symbol: 'EGLD', network: 'Elrond', icon: 'E', iconUrl: 'https://cryptologos.cc/logos/elrond-egld-egld-logo.png', color: 'text-gray-700' },
  { id: '56', name: 'Chiliz', symbol: 'CHZ', network: 'Ethereum', icon: 'C', iconUrl: 'https://cryptologos.cc/logos/chiliz-chz-logo.png', color: 'text-red-600' },
  { id: '57', name: 'Basic Attention', symbol: 'BAT', network: 'Ethereum', icon: 'B', iconUrl: 'https://cryptologos.cc/logos/basic-attention-token-bat-logo.png', color: 'text-orange-600' },
  { id: '58', name: 'Enjin Coin', symbol: 'ENJ', network: 'Ethereum', icon: 'E', iconUrl: 'https://cryptologos.cc/logos/enjin-coin-enj-logo.png', color: 'text-purple-600' },
  { id: '59', name: 'Zilliqa', symbol: 'ZIL', network: 'Zilliqa', icon: 'Z', iconUrl: 'https://cryptologos.cc/logos/zilliqa-zil-logo.png', color: 'text-teal-600' },
  { id: '60', name: 'Kusama', symbol: 'KSM', network: 'Kusama', icon: 'K', iconUrl: 'https://cryptologos.cc/logos/kusama-ksm-logo.png', color: 'text-gray-800' },
  { id: '61', name: 'Stacks', symbol: 'STX', network: 'Stacks', icon: 'S', iconUrl: 'https://cryptologos.cc/logos/stacks-stx-logo.png', color: 'text-purple-700' },
  { id: '62', name: 'Helium', symbol: 'HNT', network: 'Helium', icon: 'H', iconUrl: 'https://cryptologos.cc/logos/helium-hnt-logo.png', color: 'text-cyan-600' },
  { id: '63', name: 'Gala', symbol: 'GALA', network: 'Ethereum', icon: 'G', iconUrl: 'https://cryptologos.cc/logos/gala-gala-logo.png', color: 'text-gray-700' },
  { id: '64', name: 'Loopring', symbol: 'LRC', network: 'Ethereum', icon: 'L', iconUrl: 'https://cryptologos.cc/logos/loopring-lrc-logo.png', color: 'text-blue-600' },
  { id: '65', name: '1inch', symbol: '1INCH', network: 'Ethereum', icon: '1', iconUrl: 'https://cryptologos.cc/logos/1inch-1inch-logo.png', color: 'text-red-600' },
  { id: '66', name: 'SushiSwap', symbol: 'SUSHI', network: 'Ethereum', icon: '🍣', iconUrl: 'https://cryptologos.cc/logos/sushiswap-sushi-logo.png', color: 'text-pink-600' },
  { id: '67', name: 'Yearn Finance', symbol: 'YFI', network: 'Ethereum', icon: 'Y', iconUrl: 'https://cryptologos.cc/logos/yearn-finance-yfi-logo.png', color: 'text-blue-700' },
  { id: '68', name: 'THORChain', symbol: 'RUNE', network: 'THORChain', icon: 'R', iconUrl: 'https://cryptologos.cc/logos/thorchain-rune-logo.png', color: 'text-teal-600' },
  { id: '69', name: 'Celo', symbol: 'CELO', network: 'Celo', icon: 'C', iconUrl: 'https://cryptologos.cc/logos/celo-celo-logo.png', color: 'text-green-600' },
  { id: '70', name: 'Harmony', symbol: 'ONE', network: 'Harmony', icon: 'O', iconUrl: 'https://cryptologos.cc/logos/harmony-one-logo.png', color: 'text-cyan-500' },
  { id: '71', name: 'Holo', symbol: 'HOT', network: 'Ethereum', icon: 'H', iconUrl: 'https://cryptologos.cc/logos/holo-hot-logo.png', color: 'text-purple-600' },
  { id: '72', name: 'Qtum', symbol: 'QTUM', network: 'Qtum', icon: 'Q', iconUrl: 'https://cryptologos.cc/logos/qtum-qtum-logo.png', color: 'text-blue-500' },
  { id: '73', name: 'Ravencoin', symbol: 'RVN', network: 'Ravencoin', icon: 'R', iconUrl: 'https://cryptologos.cc/logos/ravencoin-rvn-logo.png', color: 'text-orange-600' },
  { id: '74', name: 'OMG Network', symbol: 'OMG', network: 'Ethereum', icon: 'O', iconUrl: 'https://cryptologos.cc/logos/omg-network-omg-logo.png', color: 'text-blue-600' },
  { id: '75', name: 'Waves', symbol: 'WAVES', network: 'Waves', icon: 'W', iconUrl: 'https://cryptologos.cc/logos/waves-waves-logo.png', color: 'text-blue-700' },
  { id: '76', name: 'ICON', symbol: 'ICX', network: 'ICON', icon: 'I', iconUrl: 'https://cryptologos.cc/logos/icon-icx-logo.png', color: 'text-cyan-600' },
  { id: '77', name: 'Ontology', symbol: 'ONT', network: 'Ontology', icon: 'O', iconUrl: 'https://cryptologos.cc/logos/ontology-ont-logo.png', color: 'text-teal-600' },
  { id: '78', name: 'Nano', symbol: 'XNO', network: 'Nano', icon: 'N', iconUrl: 'https://cryptologos.cc/logos/nano-xno-logo.png', color: 'text-blue-600' },
  { id: '79', name: 'Siacoin', symbol: 'SC', network: 'Siacoin', icon: 'S', iconUrl: 'https://cryptologos.cc/logos/siacoin-sc-logo.png', color: 'text-green-600' },
  { id: '80', name: 'Ankr', symbol: 'ANKR', network: 'Ethereum', icon: 'A', iconUrl: 'https://cryptologos.cc/logos/ankr-ankr-logo.png', color: 'text-blue-600' },
  { id: '81', name: 'Ren', symbol: 'REN', network: 'Ethereum', icon: 'R', iconUrl: 'https://cryptologos.cc/logos/ren-ren-logo.png', color: 'text-gray-700' },
  { id: '82', name: 'Band Protocol', symbol: 'BAND', network: 'Ethereum', icon: 'B', iconUrl: 'https://cryptologos.cc/logos/band-protocol-band-logo.png', color: 'text-blue-600' },
  { id: '83', name: 'Ocean Protocol', symbol: 'OCEAN', network: 'Ethereum', icon: 'O', iconUrl: 'https://cryptologos.cc/logos/ocean-protocol-ocean-logo.png', color: 'text-pink-500' },
  { id: '84', name: 'Fetch.ai', symbol: 'FET', network: 'Ethereum', icon: 'F', iconUrl: 'https://cryptologos.cc/logos/fetch-ai-fet-logo.png', color: 'text-blue-600' },
  { id: '85', name: 'Reserve Rights', symbol: 'RSR', network: 'Ethereum', icon: 'R', iconUrl: 'https://cryptologos.cc/logos/reserve-rights-rsr-logo.png', color: 'text-gray-700' },
  { id: '86', name: 'Arweave', symbol: 'AR', network: 'Arweave', icon: 'A', iconUrl: 'https://cryptologos.cc/logos/arweave-ar-logo.png', color: 'text-gray-700' },
  { id: '87', name: 'Injective', symbol: 'INJ', network: 'Ethereum', icon: 'I', iconUrl: 'https://cryptologos.cc/logos/injective-inj-logo.png', color: 'text-cyan-600' },
  { id: '88', name: 'Kava', symbol: 'KAVA', network: 'Kava', icon: 'K', iconUrl: 'https://cryptologos.cc/logos/kava-kava-logo.png', color: 'text-red-600' },
  { id: '89', name: 'Secret', symbol: 'SCRT', network: 'Secret', icon: 'S', iconUrl: 'https://cryptologos.cc/logos/secret-scrt-logo.png', color: 'text-gray-700' },
  { id: '90', name: 'Nervos Network', symbol: 'CKB', network: 'Nervos', icon: 'C', iconUrl: 'https://cryptologos.cc/logos/nervos-network-ckb-logo.png', color: 'text-green-600' },
  { id: '91', name: 'Convex Finance', symbol: 'CVX', network: 'Ethereum', icon: 'C', iconUrl: 'https://cryptologos.cc/logos/convex-finance-cvx-logo.png', color: 'text-gray-700' },
  { id: '92', name: 'Rocket Pool', symbol: 'RPL', network: 'Ethereum', icon: 'R', iconUrl: 'https://cryptologos.cc/logos/rocket-pool-rpl-logo.png', color: 'text-orange-600' },
  { id: '93', name: 'Frax', symbol: 'FRAX', network: 'Ethereum', icon: 'F', iconUrl: 'https://cryptologos.cc/logos/frax-frax-logo.png', color: 'text-gray-700' },
  { id: '94', name: 'TrueUSD', symbol: 'TUSD', network: 'Ethereum', icon: 'T', iconUrl: 'https://cryptologos.cc/logos/trueusd-tusd-logo.png', color: 'text-blue-600' },
  { id: '95', name: 'Pax Dollar', symbol: 'USDP', network: 'Ethereum', icon: 'P', iconUrl: 'https://cryptologos.cc/logos/paxos-standard-pax-logo.png', color: 'text-green-600' },
  { id: '96', name: 'Gemini Dollar', symbol: 'GUSD', network: 'Ethereum', icon: 'G', iconUrl: 'https://cryptologos.cc/logos/gemini-dollar-gusd-logo.png', color: 'text-blue-600' },
  { id: '97', name: 'USD Coin', symbol: 'USDC', network: 'Ethereum', icon: 'C', iconUrl: 'https://cryptologos.cc/logos/usd-coin-usdc-logo.png', color: 'text-blue-600' },
  { id: '98', name: 'Dai', symbol: 'DAI', network: 'Ethereum', icon: 'D', iconUrl: 'https://cryptologos.cc/logos/multi-collateral-dai-dai-logo.png', color: 'text-yellow-600' },
  { id: '99', name: 'Binance USD', symbol: 'BUSD', network: 'BSC', icon: 'B', iconUrl: 'https://cryptologos.cc/logos/binance-usd-busd-logo.png', color: 'text-yellow-600' },
  { id: '100', name: 'Wrapped Bitcoin', symbol: 'WBTC', network: 'Ethereum', icon: '₿', iconUrl: 'https://cryptologos.cc/logos/wrapped-bitcoin-wbtc-logo.png', color: 'text-orange-500' },
  { id: '101', name: 'Staked Ether', symbol: 'stETH', network: 'Ethereum', icon: 'Ξ', iconUrl: 'https://cryptologos.cc/logos/steth-steth-logo.png', color: 'text-purple-600' },
  { id: '102', name: 'Pepe', symbol: 'PEPE', network: 'Ethereum', icon: '🐸', iconUrl: 'https://cryptologos.cc/logos/pepe-pepe-logo.png', color: 'text-green-600' },
  { id: '103', name: 'Render', symbol: 'RNDR', network: 'Ethereum', icon: 'R', iconUrl: 'https://cryptologos.cc/logos/render-token-rndr-logo.png', color: 'text-orange-600' },
  { id: '104', name: 'MultiversX', symbol: 'EGLD', network: 'MultiversX', icon: 'M', iconUrl: 'https://cryptologos.cc/logos/multiversx-egld-egld-logo.png', color: 'text-gray-700' },
  { id: '105', name: 'Kaspa', symbol: 'KAS', network: 'Kaspa', icon: 'K', iconUrl: 'https://cryptologos.cc/logos/kaspa-kas-logo.png', color: 'text-blue-600' }
];

export const getNetworkMapping = (): { [network: string]: string } => {
  const mapping: { [key: string]: string } = {};
  cryptoDataList.forEach(crypto => {
    mapping[crypto.network] = crypto.network;
  });
  return mapping;
};
